### ISSUE TITLE
Usernames not being retained for token refreshes

### ISSUE THREAD

**Issue by rtrvrtg** [anchor/oauth2-server#25]
This problem appears to be the cause of https://github.com/anchor/anchor-apis/issues/139

As noted in https://github.com/anchor/oauth2-server/blob/master/oauth2-server/lib/Network/OAuth2/Server.hs#L73 the username must be copied across from the original request. However, this is not currently being done, and there doesn't seem to be an obvious way to do this.

**Comment by rtrvrtg** [comment]
Looks like `RequestRefresh` will probably need to have an additional username field added to it, and the assorted servers will need to be updated to accomodate it.

**Comment by thsutton** [comment]
You decode the `Token` in `RequestRefresh{requestRefreshToken}` and replace the `Nothing` with whatever is in that token.

This will require a refactor so that the `AnchorToken` handlers are available in this function.
