### ISSUE TITLE
Refresh should revoke existing access and refresh tokens

### ISSUE THREAD

**Issue by thsutton** [anchor/oauth2-server#72]
A refresh_token grant should revoke any existing access and refresh tokens being replaced.

**Comment by christian-marie** [comment]
(Should probably revoke first, too, if that wasn't obvious)

**Comment by thsutton** [comment]
Should probably revoke the original refresh token iff we could generate a new one. We don't to have a transient failure take away all their creds, right?

**Comment by christian-marie** [comment]
I suppose, so long as the token never reaches the client without the old one being revoked we're OK.

**Comment by thsutton** [comment]
This was fixed (though the fix needs refactoring) in #104.
